import = [
  "~/.config/alacritty/themes/themes/tokyo-night.toml"
]
[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.7

[window.padding]
x = 8
y = 6
