tap "koekeishiya/formulae"

brew "eza"
brew "fish"
brew "neovim"
brew "stow"
brew "tmux"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
cask "alfred"
cask "bitwarden"
cask "claude"
cask "dropbox"
cask "ghostty"
cask "google-chrome"
cask "karabiner-elements"
cask "spotify"
