# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows
    # gaps_in = 0
    # gaps_out = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 8
}

# Workspace names
workspace = 1, name:emacs
workspace = 2, name:web

# === a-la-carchy hyprland settings ===
gesture = 3, horizontal, workspace
# === end a-la-carchy hyprland settings ===
