name: Gitleaks Guard

on:
  push:
    branches:
      - main

jobs:
  run-gitleaks:
    name: Scan with gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_CONFIG: .gitleaks.toml
          GITLEAKS_NOTIFY_USER_LIST: @eapolinario
